### ISSUE TITLE
Dataset DFDC Frames extraction

### ISSUE THREAD

**Issue by IpekUyguner** [pterhoer/DeepFakeAnnotations#1]
Hi,

For DFDC dataset, would you also provide the frames themselves( or they are already public)or should I extract them from videos of DFDC myself? 

Thank you for your work!

**Comment by xuyingzhongguo** [comment]
> Hi,
> 
> For DFDC dataset, would you also provide the frames themselves( or they are already public)or should I extract them from videos of DFDC myself?
> 
> Thank you for your work!

Hi,

I am willing to share the code that I extract faces from each frame. I am not with my laptop this week so I will update the comment next week.

**Comment by xuyingzhongguo** [comment]
Please refer to this [code](https://github.com/xuyingzhongguo/DFDC_face_extract.git) for face extraction of DFDC.
